version: "3.3"
services:
    yoofood-back:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - TZ=America/Sao_Paulo
        ports:
            - "3011:3010"
        command: npm run dev